#!/bin/bash

# zeeree command script

case "$1" in
    init)
        ./scripts/init.sh
        ;;
    refresh)
        ./scripts/after-resolve.sh
        ;;
    *)
        echo "Usage: zeeree {init}"
        exit 1
        ;;
esac
