#!/bin/bash

# zeeree command script
LIB_DIR="/usr/local/lib/xcrone/git-zeeree"

case "$1" in
    init)
        /bin/bash -c $LIB_DIR/scripts/init.sh
        ;;
    after-resolve)
        /bin/bash -c $LIB_DIR/scripts/after-resolve.sh
        ;;
    *)
        echo "Usage: zeeree {init, after-resolve}"
        exit 1
        ;;
esac
