#!/bin/bash

# zeeree command script
LIB_DIR="/usr/local/lib/xcrone/git-zeeree"

case "$1" in
    init)
        /bin/bash -c "$(./scripts/init.sh)"
        ;;
    refresh)
        /bin/bash -c "$(./scripts/after-resolve.sh)"
        ;;
    *)
        echo "Usage: zeeree {init}"
        exit 1
        ;;
esac
